services:
  - type: web
    name: chest-xray-api
    runtime: python
    plan: free
    buildCommand: |
      # Skip Git LFS during clone to avoid LFS quota issues
      export GIT_LFS_SKIP_SMUDGE=1
      # Install system dependencies for OpenCV and magic
      apt-get update && apt-get install -y \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev \
        libgomp1 \
        libmagic1 \
        libmagic-dev \
        build-essential || true
      pip install --upgrade pip setuptools wheel
      # Install packages with no-cache to avoid issues
      pip install --no-cache-dir -r requirements.txt
      # Create upload directories in case they don't exist
      mkdir -p uploads/training/normal uploads/training/pneumonia uploads/temp
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: ENVIRONMENT
        value: production
      - key: GIT_LFS_SKIP_SMUDGE
        value: "1"
      - key: DISABLE_COLLECTSTATIC
        value: 1
