services:
  - type: web
    name: chest-xray-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: ENVIRONMENT
        value: production
