services:
  - type: web
    name: chest-xray-api
    runtime: python
    plan: free
    buildCommand: |
      # Install system dependencies for OpenCV and magic
      apt-get update && apt-get install -y \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev \
        libgomp1 \
        libmagic1 \
        libmagic-dev || true
      pip install --upgrade pip
      pip install -r requirements.txt
      # Create upload directories in case they don't exist
      mkdir -p uploads/training/normal uploads/training/pneumonia uploads/temp
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
